//
// Created by Jamie on 5/16/2019.
//

#ifndef COMPILERASSIGNMENT_ASTFUNCTIONDECLSTATEMENT_H
#define COMPILERASSIGNMENT_ASTFUNCTIONDECLSTATEMENT_H


class ASTFunctionDeclStatement {

};


#endif //COMPILERASSIGNMENT_ASTFUNCTIONDECLSTATEMENT_H
