//
// Created by Jamie on 5/16/2019.
//

#ifndef COMPILERASSIGNMENT_ASTIDENTIFIERNODE_H
#define COMPILERASSIGNMENT_ASTIDENTIFIERNODE_H


class ASTIdentifierNode {

};


#endif //COMPILERASSIGNMENT_ASTIDENTIFIERNODE_H
