//
// Created by Jamie on 5/16/2019.
//

#ifndef COMPILERASSIGNMENT_ASTSIMPLEEXPRESSION_H
#define COMPILERASSIGNMENT_ASTSIMPLEEXPRESSION_H


class ASTSimpleExpression {

};


#endif //COMPILERASSIGNMENT_ASTSIMPLEEXPRESSION_H
