//
// Created by Jamie on 5/16/2019.
//

#ifndef COMPILERASSIGNMENT_ASTVARIABLEDECLSTATEMENT_H
#define COMPILERASSIGNMENT_ASTVARIABLEDECLSTATEMENT_H


class ASTVariableDeclStatement {

};


#endif //COMPILERASSIGNMENT_ASTVARIABLEDECLSTATEMENT_H
