//
// Created by Jamie on 5/22/2019.
//

#ifndef COMPILERASSIGNMENT_XMLGENERATIONVISITOR_H
#define COMPILERASSIGNMENT_XMLGENERATIONVISITOR_H


class XMLGenerationVisitor {

};


#endif //COMPILERASSIGNMENT_XMLGENERATIONVISITOR_H
